apiVersion: v1
kind: Service
metadata:
  name: url-shortening-service-svc
spec:
  selector:
    app: url-shortening-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort