spring:
  application:
    name: url-shortening-service
  datasource:
    url: jdbc:h2:file:./data/demo;AUTO_SERVER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
host:
  base-url: "http://localhost:8080/"
url-params:
  length: 7
  attempts: 5
server:
  port: 8080
